[CmdletBinding()]
param(
    [string]$ControllersPath = 'E:\Backend Projects\ITI_Project\ITI_Project.Api\Controllers',
    [string]$OutputPath = 'E:\Backend Projects\ITI_Project\API_Documentation.txt'
)

$ErrorActionPreference = 'Stop'

function Get-ControllerName([string]$fileName) {
    return ([System.IO.Path]::GetFileNameWithoutExtension($fileName) -replace 'Controller$','')
}

function Get-HttpVerbAndTemplate([string]$attrLine) {
    $line = $attrLine.Trim()

    if ($line.StartsWith('[HttpGet', 'OrdinalIgnoreCase'))    { $verb = 'GET' }
    elseif ($line.StartsWith('[HttpPost', 'OrdinalIgnoreCase')) { $verb = 'POST' }
    elseif ($line.StartsWith('[HttpPut', 'OrdinalIgnoreCase'))  { $verb = 'PUT' }
    elseif ($line.StartsWith('[HttpDelete', 'OrdinalIgnoreCase')) { $verb = 'DELETE' }
    elseif ($line.StartsWith('[HttpPatch', 'OrdinalIgnoreCase')) { $verb = 'PATCH' }
    else { return $null }

    $template = ''
    $m = [regex]::Match($line, '"([^"]+)"')
    if ($m.Success) { $template = $m.Groups[1].Value }

    return [pscustomobject]@{ Verb = $verb; Template = $template }
}

function Get-ActionName([string]$signatureLine) {
    $m = [regex]::Match($signatureLine, '\s(\w+)\s*\(')
    if ($m.Success) { return $m.Groups[1].Value }
    return 'Unknown'
}

function Get-AuthorizationText([string[]]$attributeBlock) {
    $authAttrs = $attributeBlock | Where-Object { $_.Trim().StartsWith('[Authorize', 'OrdinalIgnoreCase') }
    if (-not $authAttrs -or $authAttrs.Count -eq 0) {
        return 'Anonymous/Not specified'
    }

    # Keep it accurate by returning the raw attribute line(s)
    return ($authAttrs -join ' | ')
}

function Get-StatusCodes([string[]]$methodBodyLines) {
    $text = ($methodBodyLines -join "`n")
    $codes = New-Object System.Collections.Generic.HashSet[int]

    foreach ($m in [regex]::Matches($text, 'StatusCodes\\.Status(\\d{3})')) {
        [void]$codes.Add([int]$m.Groups[1].Value)
    }

    if ($text -match '\bCreatedAtAction\s*\(') { [void]$codes.Add(201) }
    if ($text -match '\bOk\s*\(')            { [void]$codes.Add(200) }
    if ($text -match '\bNoContent\s*\(')     { [void]$codes.Add(204) }
    if ($text -match '\bBadRequest\s*\(')    { [void]$codes.Add(400) }
    if ($text -match '\bUnauthorized\s*\(')  { [void]$codes.Add(401) }
    if ($text -match '\bForbid\s*\(')        { [void]$codes.Add(403) }
    if ($text -match '\bNotFound\s*\(')      { [void]$codes.Add(404) }
    if ($text -match '\bConflict\s*\(')      { [void]$codes.Add(409) }
    if ($text -match 'StatusCode\s*\(\s*500\s*\)') { [void]$codes.Add(500) }

    if ($codes.Count -eq 0) { [void]$codes.Add(200) }

    return ($codes | Sort-Object)
}

if (-not (Test-Path -LiteralPath $ControllersPath)) {
    throw "Controllers path not found: $ControllersPath"
}

$sb = [System.Text.StringBuilder]::new()

[void]$sb.AppendLine('ITI_Project API - Endpoint Documentation')
[void]$sb.AppendLine(('Generated: {0:yyyy-MM-dd HH:mm:ss} (local)' -f (Get-Date)))
[void]$sb.AppendLine('Base URL Prefix: /api')
[void]$sb.AppendLine('')
[void]$sb.AppendLine('Notes:')
[void]$sb.AppendLine('- This document is generated by scanning controller source code (*.cs).')
[void]$sb.AppendLine('- Authorization is shown as the raw [Authorize(...)] attribute when present.')
[void]$sb.AppendLine('- Status codes are inferred from return statements and StatusCodes.StatusXXX usage in method bodies.')
[void]$sb.AppendLine('')

$controllerFiles = Get-ChildItem -LiteralPath $ControllersPath -Recurse -Filter '*Controller.cs' | Sort-Object FullName

foreach ($file in $controllerFiles) {
    $lines = Get-Content -LiteralPath $file.FullName
    $controllerName = Get-ControllerName $file.Name
    $baseRoute = "/api/$controllerName"
    $rel = $file.FullName.Replace($PSScriptRoot + [System.IO.Path]::DirectorySeparatorChar, '')

    [void]$sb.AppendLine('================================================================================')
    [void]$sb.AppendLine(("Controller: {0}" -f $controllerName))
    [void]$sb.AppendLine(("Route Base: {0}" -f $baseRoute))
    [void]$sb.AppendLine(("Source: {0}" -f $rel))
    [void]$sb.AppendLine('================================================================================')
    [void]$sb.AppendLine('')

    for ($i = 0; $i -lt $lines.Count; $i++) {
        $http = Get-HttpVerbAndTemplate $lines[$i]
        if ($null -eq $http) { continue }

        # Gather attribute block (including [Authorize], [ServiceFilter], etc.) directly above the [Http*] line.
        $attrBlock = New-Object System.Collections.Generic.List[string]
        $attrBlock.Add($lines[$i].Trim())

        $j = $i - 1
        while ($j -ge 0) {
            $t = $lines[$j].Trim()
            if (-not $t.StartsWith('[')) { break }
            $attrBlock.Insert(0, $t)
            $j--
        }

        # Find method signature line
        $k = $i + 1
        while ($k -lt $lines.Count -and ($lines[$k].Trim().Length -eq 0 -or -not $lines[$k].Trim().StartsWith('public'))) {
            $k++
        }
        if ($k -ge $lines.Count) { continue }

        $signature = $lines[$k].Trim()
        $actionName = Get-ActionName $signature

        $path = $baseRoute
        if (-not [string]::IsNullOrWhiteSpace($http.Template)) {
            if ($http.Template.StartsWith('/')) {
                $path = $http.Template
            }
            else {
                $path = ($baseRoute.TrimEnd('/') + '/' + $http.Template.TrimStart('/'))
            }
        }

        $authText = Get-AuthorizationText $attrBlock

        # Capture method body lines (best-effort) to infer status codes.
        $bodyLines = New-Object System.Collections.Generic.List[string]

        # Find the first opening brace for this method
        $m = $k
        while ($m -lt $lines.Count -and $lines[$m] -notmatch '{') { $m++ }
        if ($m -ge $lines.Count) {
            $statusCodes = @(200)
        }
        else {
            $braceDepth = 0
            for (; $m -lt $lines.Count; $m++) {
                $line = $lines[$m]
                $bodyLines.Add($line)
                $braceDepth += ([regex]::Matches($line, '{')).Count
                $braceDepth -= ([regex]::Matches($line, '}')).Count
                if ($braceDepth -eq 0 -and $m -gt $k) { break }
            }
            $statusCodes = Get-StatusCodes $bodyLines
        }

        [void]$sb.AppendLine(("{0} {1}" -f $http.Verb, $path))
        [void]$sb.AppendLine(("  Action: {0}" -f $actionName))
        [void]$sb.AppendLine(("  Authorization: {0}" -f $authText))
        [void]$sb.AppendLine(("  Status Codes: {0}" -f ($statusCodes -join ', ')))
        [void]$sb.AppendLine('')
    }

    [void]$sb.AppendLine('')
}

Set-Content -LiteralPath $OutputPath -Value $sb.ToString() -Encoding UTF8
Write-Host "Documentation generated: $OutputPath"
